### ISSUE TITLE
Question: Is this project abandond?

### ISSUE THREAD

**Issue by blairham** [akshaykarle/terraform-provider-mongodbatlas#101]
I haven't seen much movement on this provider and before I start relying on it I need to know if this code is abandoned or active.

**Comment by Knappek** [comment]
That's a very good question, I'm also wondering, especially because there is another repo from mongodb: https://github.com/mongodb/terraform-provider-mongodbatlas

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by blairham** [comment]
I think that is the official supported project, thanks for pointing it out I will switch over to that one now

**Comment by Knappek** [comment]
I'm not entirely sure, they just created it a couple of days ago, it is still confusing...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arthurio** [comment]
It’s really confusing and I couldn’t get their version to build... So until they announce it’s official I’m sticking to @akshaykarle’s version

**Comment by blairham** [comment]
So it looks like MongoDB Atlas has taken over this project, I've pulled and built it and tested it this morning. There are a few breaking changes that need to be addressed. They renamed a few resources and change some attributes. over all it works.

There is reference at the bottom of their readme that thanks @akshaykarle  for his work. They are currently in review with Terraform as to making it a public release. I would wait on that but the good news is they have fixed numerous bugs and provide a ton more data resources

**Comment by arthurio** [comment]
I guess they did announce it: https://www.mongodb.com/blog/post/terraform-and-vault-are-coming-to-mongodb-atlas

I'll switch :) (Thanks for your @akshaykarle though 🙏 )

**Comment by themantissa** [comment]
Hi all!  I'm the author of the above blog post and yes, MongoDB has an official Terraform Provider (https://github.com/mongodb/terraform-provider-mongodbatlas) for MongoDB Atlas that we are working on.  It's still in development by a 3rd party firm for v1 but as the blog notes the repo is open so you can follow along and we are indeed in the review process with Hashicorp.  

It is a net new rewrite so that we could be sure we are using the most recent version of the API (no deprecate API resources) so there will be differences.   Full doc is being worked on (you can see it in the repo) and once completed we can work on some examples of a full deployment as well.  

Feel free to message me directly and/or file issues/questions in the repo as we move forward.  

We really appreciate all the work @akshaykarle did on this version, it was instrumental in seeing the demand!

**Comment by nitrag** [comment]
Thanks for clarifying @themantissa, this repo (by @akshaykarle) is still working fine for those that can't wait.
